---
title: "Bias Correction and Evaluation of results"
author: "Henri Funk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bias Correction and Evaluation of results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
rm(list = ls())
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>"
)
devtools::load_all()
```

```{r lib, message=FALSE, warning=FALSE}
library(rvinecopulib)
library(MBC)
library(ggplot2)
library(patchwork)
library(corrplot)
library(kde1d)
library(parallel)
library(lubridate)
library(ggdensity)
library(data.table)
library(ggridges)
```

# Data Inspection

```{r data, out.width="100%"}
data(climate)
summerday = lapply(climate, function(dta) {
  summer = dta[hour(time) %in% c(18, 15, 12, 9) & month(time) %in% c(7, 8, 9), ]
  list(
    whole = summer,
    train = summer[year(time) %in% 1991:1995, ],
    test = summer[year(time) %in% 1996:2000, ]
  )
} 
  )


ggplot(summer_climate$oc) +
  geom_hdr(aes(x = dew, y = sfcWind, fill = after_stat(probs)),
           show.legend = FALSE) 

summary(summer_climate$oc)
k_tau <- cor(summer_climate$oc[, -6], method = "kendall")
apply(k_tau, 1, function(x) sum(abs(x)))

corrplot(k_tau, method = "color",  addCoef.col = "black", type = "lower",
         order = "original", sig.level = 0.1, insig = "blank", diag=FALSE)
```

# Correct the Bias

## Vine Correction

```{r vbc_summer}
margins_controls <- list(xmin = c(NaN, 0, NaN, 0, 0))
zero_inf <- c(FALSE, TRUE, FALSE, FALSE, FALSE)
start = Sys.time()
#debugonce(vine_correct)
vbc <- vine_correct(oc = summerday$oc$train[, -6], mc = summerday$mc$train[,-6],
                    mp = summerday$mc$test[,-6], margins_controls = margins_controls,
                    family_set = "tll", zero_inf = zero_inf, trunc_lvl = NA,
                    selcrit = "mbicv", psi0 = 0.9)
Sys.time() - start


calc_wasserstein(vbc, summerday$oc$test[, -6])
attr(calc_mci(vbc, summerday$mc$test[,-6]), "global")


summary(attr(vbc, "vine_oc"))
plot(attr(vbc, "vine_oc"), 1)
contour(attr(vbc, "vine_oc"))
summary(attr(vbc, "vine_mp"))
plot(attr(vbc, "vine_mp"), 4)
contour(attr(vbc, "vine_mp"))
summary(summer_climate$oc)
summary(vbc)


plot(attr(vbc, "kde_oc")[[1]])
plot(attr(vbc, "kde_mp")[[1]])
plot(density(vbc[, 1]))
```


## Univariate Correction

```{r ubc, warning=FALSE}
is_rat = c(FALSE, TRUE, FALSE, TRUE, TRUE)
ubc <- mapply(QDM, o.c = summerday$oc$train[, -6],
              m.c = summerday$mc$train[, -6], m.p = summerday$mc$test[, -6],
              ratio = is_rat, trace = ifelse(is_rat, 0.05, Inf),
              SIMPLIFY = FALSE)
ubc <- do.call(cbind.data.frame, lapply(ubc, function(var) var$mhat.p))
```

## Multivariate Correction

```{r mbcn, warning=FALSE}
mbcn <- MBCn(o.c = summerday$oc$train[, -6], m.c = summerday$mc$train[, -6],
             m.p = summerday$mc$test[, -6], ratio.seq = is_rat,
             trace = ifelse(is_rat, 0.05, Inf), silent = TRUE)$mhat.p
colnames(mbcn) <- colnames(summerday$oc$train[, -6])
```

# Evaluation

```{r}
calc_wasserstein(mbcn, summerday$oc$test[, -6])
calc_wasserstein(ubc, summerday$oc$test[, -6])
calc_wasserstein(vbc, summerday$oc$test[, -6])

attr(calc_mci(mbcn, summerday$mc$test[, -6]), "global")
attr(calc_mci(ubc, summerday$mc$test[, -6]), "global")
attr(calc_mci(vbc, summerday$mc$test[, -6]), "global")
```



```{r zero_count}
correction = rbindlist(list(
  cbind(summerday$oc$test[, -6], correction = "oc"),
  cbind(data.frame(mbcn), correction = "mbcn"),
  cbind(data.frame(ubc), correction = "ubc"),
  cbind(data.frame(vbc), correction = "vbc")
))

c(
  "measured data cali" = sum(summerday$oc$train[, "pr"] == 0),
  "measured data proj" = sum(summerday$oc$test[, "pr"] == 0),
  "univariate correction" = sum(ubc[, "pr"] == 0),
  "multivarite correction by Cannon" = sum(mbcn[, "pr"] == 0),
  "vine copula correction" = sum(vbc[, "pr"] == 0)
)

c(
  "measured data cali" = sum(summerday$oc$train[, "rsds"] == 0),
  "measured data proj" = sum(summerday$oc$test[, "rsds"] == 0),
  "univariate correction" = sum(ubc[, "rsds"] == 0),
  "multivarite correction by Cannon" = sum(mbcn[, "rsds"] == 0),
  "vine copula correction" = sum(vbc[, "rsds"] == 0)
)
```

## Densities

### Visual Comparison between Termperature Range (dtr) and Windspeed (sfcWind)


```{r origin, warning=FALSE}
ggplot(correction) +
  geom_hdr(aes(x = tas, y = dew, fill = after_stat(probs)),
           show.legend = FALSE) +
  facet_wrap(~correction)



ggplot(correction, aes(x = tas, y = correction, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)

ggplot(correction, aes(x = pr, y = correction, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1) + xlim(c(0, 3))

ggplot(correction, aes(x = dew, y = correction, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)

ggplot(correction, aes(x = rsds, y = correction, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)

ggplot(correction, aes(x = sfcWind, y = correction, fill = 0.5 - abs(0.5 - stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)

correction[, lapply(.SD, function(x) calc_wasserstein(observed = x, model = summer_climate$mc[, -6]), by = correction)]


```         

```{r, eval = FALSE}
seasons = list(winter = c(12, 1, 2), spring = c(3, 4, 5), summer = c(6, 7, 8),
               autumn = c(9, 10, 11))

seasons_night = mclapply(seasons, function(season) {
  seasonal_climate = lapply(climate, function(dta) dta[
  hour(time) %in% c(21, 0, 3, 6) & month(time) %in% season, ]
  )
  
  margins_controls <- list(xmin = c(NaN, 0, NaN, 0, 0))
  zero_inf <- c(FALSE, TRUE, FALSE, TRUE, FALSE)
  
  vbc <- vine_correct(oc = seasonal_climate$oc[, -6],
                      mc = seasonal_climate$mc[, -6],
                      mp = seasonal_climate$mp[, -6],
                      margins_controls = margins_controls, zero_inf = zero_inf,
                      trunc_lvl = NA, var_types = c("c", "d", "c", "d", "c"),
                      selcrit = "mbicv", psi0 = 1e-6)
  vbc <- cbind(vbc, time = seasonal_climate$mp[, 6])
  
  is_rat = c(FALSE, TRUE, FALSE, TRUE, TRUE)
  ubc <- mapply(QDM, o.c = seasonal_climate$oc[, -6], 
                m.c = seasonal_climate$mc[, -6],
                m.p = seasonal_climate$mp[, -6],
                ratio = is_rat, trace = ifelse(is_rat, 0.05, Inf),
                SIMPLIFY = FALSE)
  ubc <- do.call(cbind.data.frame, lapply(ubc, function(var) var$mhat.p))
  ubc <- cbind(ubc, time = seasonal_climate$mp[, 6])
  
  mbcn <- MBCn(o.c = seasonal_climate$oc[, -6],
               m.c = seasonal_climate$mc[, -6],
               m.p = seasonal_climate$mp[, -6], ratio.seq = is_rat,
             trace = ifelse(is_rat, 0.05, Inf), silent = TRUE)$mhat.p
  mbcn = cbind.data.frame(mbcn, time = seasonal_climate$mp[, 6])
  colnames(mbcn) <- colnames(seasonal_climate)
  
  list(vbc = vbc, ubc = ubc, mbcn = mbcn)
  
}, mc.cores = 4)

seasons_day = mclapply(seasons, function(season) {
  seasonal_climate = lapply(climate, function(dta) dta[
  hour(time) %in% c(9, 12, 15, 18) & month(time) %in% season, ]
  )
  
  margins_controls <- list(xmin = c(NaN, 0, NaN, 0, 0))
  zero_inf <- c(FALSE, TRUE, FALSE, TRUE, FALSE)
  
  vbc <- vine_correct(oc = seasonal_climate$oc[, -6],
                      mc = seasonal_climate$mc[, -6],
                      mp = seasonal_climate$mp[, -6],
                      margins_controls = margins_controls, zero_inf = zero_inf,
                      trunc_lvl = NA, var_types = c("c", "d", "c", "d", "c"),
                      selcrit = "mbicv", psi0 = 1e-6)
  vbc <- cbind(vbc, time = seasonal_climate$mp[, 6])
  
  is_rat = c(FALSE, TRUE, FALSE, TRUE, TRUE)
  ubc <- mapply(QDM, o.c = seasonal_climate$oc[, -6], 
                m.c = seasonal_climate$mc[, -6],
                m.p = seasonal_climate$mp[, -6],
                ratio = is_rat, trace = ifelse(is_rat, 0.05, Inf),
                SIMPLIFY = FALSE)
  ubc <- do.call(cbind.data.frame, lapply(ubc, function(var) var$mhat.p))
  ubc <- cbind(ubc, time = seasonal_climate$mp[, 6])
  
  mbcn <- MBCn(o.c = seasonal_climate$oc[, -6],
               m.c = seasonal_climate$mc[, -6],
               m.p = seasonal_climate$mp[, -6], ratio.seq = is_rat,
             trace = ifelse(is_rat, 0.05, Inf), silent = TRUE)$mhat.p
  mbcn = cbind.data.frame(mbcn, time = seasonal_climate$mp[, 6])
  colnames(mbcn) <- colnames(seasonal_climate)
  
  list(vbc = vbc, ubc = ubc, mbcn = mbcn)
  
}, mc.cores = 4)

corrections = lapply(c("ubc", "vbc", "mbcn"), function(cor) {
  dta = rbindlist(lapply(c(seasons_day, seasons_night), function(x) x[[cor]]))
  colnames(dta)  = colnames(summer_climate$oc)
  dta[, time := as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")]
  dta[order(time)]
})
corrections = c(corrections, list(climate$mp))
names(corrections) = c("ubc", "vbc", "mbcn", "model_proj")
wds = mclapply(corrections, function(cor){
  lapply(1:25, function(seed){
    set.seed(seed)
    data.frame(t(calc_wasserstein(cor[, -6], climate$op[, -6], n = 1e4)))
  })
}, mc.cores = 2)

wds = rbindlist(
  mapply(function(wd, cor) {
    cbind(rbindlist(wd), correction = cor)
  }, wd = wds, cor = names(wds), SIMPLIFY = FALSE)
)

saveRDS(corrections, "../data/corrections.RDS")
saveRDS(wds, "../data/wd.RDS")
```

```{r}
corrections = readRDS("../data/corrections.RDS")
wds = readRDS("../data/wd.RDS")
```


```{r global_eval}

mcis = lapply(corrections[1:3], function(cor) {
  calc_mci(climate$mp, cor, norm = 2)
})

global_mci = lapply(mcis, function(x) attr(x, "global"))

ggplot(wds, aes(x = correction, y = Wasserstein_2, colour = correction)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.5)


# Precip
lapply(c(corrections, obs_proj = list(climate$op)), function(x) sum(x[,2] == 0))
# RSDS
lapply(c(corrections, obs_proj = list(climate$op)), function(x) sum(x[,4] == 0))

corretions_dta = mapply(function(cor, n){
  cor[, correction := n]
}, cor = corrections, n = names(corrections), SIMPLIFY = FALSE)
corretions_dta$model_proj = corretions_dta$model_proj[, time := as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")]
corretions_dta = rbind(rbindlist(corretions_dta),
                       cbind(climate$op, correction = "observed")[, time := as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")])


ggplot(corretions_dta, aes(x = sfcWind, y = correction, 
                           fill = 0.5 - abs(0.5 - after_stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)
ggplot(corretions_dta, aes(x = rsds, y = correction, 
                           fill = 0.5 - abs(0.5 - after_stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1) +
  xlim(c(0, 1.5e3))
ggplot(corretions_dta, aes(x = dew, y = correction, 
                           fill = 0.5 - abs(0.5 - after_stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)
ggplot(corretions_dta, aes(x = tas, y = correction, 
                           fill = 0.5 - abs(0.5 - after_stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)
ggplot(corretions_dta[pr != 0, ], aes(x = pr, y = correction, 
                           fill = 0.5 - abs(0.5 - after_stat(ecdf)))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Tail probability", direction = -1)+
  xlim(c(0, 3))

ggplot(corretions_dta) +
  geom_hdr(aes(x = tas, y = dew, fill = after_stat(probs)),
           show.legend = FALSE) +
  facet_wrap(~correction)
ggplot(corretions_dta[rsds != 0,]) +
  geom_hdr(aes(x = rsds, y = tas, fill = after_stat(probs)),
           show.legend = FALSE) +
  facet_wrap(~correction)

```


### Rank Preservance



```{r}
unlist(lapply(mci, function(x) attr(x, "global")))


plot_barcode(mci$vbc, "mci", low = "#FFCBD1", high = "#C30010",  guide = "none",
             breaks = seq(0, 5, length.out = 3), limits = c(0, 5)) +
plot_barcode(mci$mbcn, "mci", low = "#FFCBD1", high = "#C30010",  guide = "none",
             breaks = seq(0, 5, length.out = 3), limits = c(0, 5)) +
  plot_layout(nrow = 2)

summary(vbc)
ggplot(cbind(vbc, time = summer_climate$mp$time)[1:50,], aes(y = dew, x = time), colour = "green") +
  geom_point(colour = "green") +
  geom_point(data = summer_climate$mp[1:50,], mapping = aes(y = dew, x = time), colour = "red") +
  geom_point(data = cbind(data.frame(mbcn), time = summer_climate$mp$time)[1:50,], mapping = aes(y = dew, x = time), colour = "blue")
```



